# Generated by Django 3.1.6 on 2021-03-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
